# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a79188a9fb7091998b3f0b7d49b1b1278aa782cdec9ca899c5d4d584963ea28e9c85729936396fd465462da8d6b944b7338641081a4684f3368bd4a790a9a70

test:
  secret_key_base: d011c9b07f2b6365e8bade3db0ee305a03fd85e8fc5e279b1137c1247934560762dbcd83eae43dc8c2242c4edffa8fc9f49ecbdb75c1ec9ba496eee122ea3272

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
